version: '3'
services:
  backend_node:
    container_name: node_agenda
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: pm2-runtime start app.js

  nginx:
    image: nginx:alpine
    container_name: iw_parcial_pregunta11
    ports:
      - "8089:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend_node
